server:
  port: 1101
spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl :
      defaultZone: http://localhost:1024/eureka/
# 服务发现机制
zuul:
  routes:
    user-consumer:
      path: /eureka-consumer/**
      serviceId: eureka-consumer

# 传统路由方式，不依靠服务发现机制
#    user-service:
#      path: /user-service/**
#      url: http://localhost:1090/
#    hello-service:
#      path: /hello-service/**
#      url: http://localhost:2048/
