spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tianruoliu/config-repo-demo
          username: tianruoliu
          password: charlene1



server:
  port: 1800
